[project]
name = "cashew-banker"
version = "0.1.0"
description = "A streamlit-powered converter that transforms uploaded bank statements (PDF, CSV, XLSX) into Cashew format with auto-categorization via Gemini API"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
